# Generated by Django 5.1.1 on 2025-11-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
