# Generated by Django 5.1.1 on 2025-11-23 17:24

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer_auth', '0002_apikey_revoked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='id',
            field=models.UUIDField(default=secrets.token_urlsafe, editable=False, primary_key=True, serialize=False),
        ),
    ]
