# Generated by Django 5.1.1 on 2024-09-30 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_order_at_order_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.cart'),
            preserve_default=False,
        ),
    ]
